### ISSUE TITLE
Did the vsicons.presets.foldersAllDefaultIcon get removed?

### ISSUE THREAD

**Issue by mcfarljw** [vscode-icons/vscode-icons#1562]
I noticed recently that my plain boring folder icons have now started showing some custom icons. I want my files to use the icons from this pack, but have my folders remain as just plain folder icons.

**Comment by robertohuertasm** [comment]
@mcfarljw, did @JimiC 's advise fix your issue?

**Comment by mcfarljw** [comment]
No, I still see special folder icons based on the name rather than default
identical ones.

**Comment by robertohuertasm** [comment]
So, you have `"vsicons.presets.foldersAllDefaultIcon": true` in your `USER SETTINGS` (not the Workspace settings!) and yet you see special folder icons? It should be working. I've just tried and cannot reproduce your issue.

Have you tried reinstalling the extension?

**Comment by kspearrin** [comment]
This has happened twice to me in the past couple of months. Toggling from true => false => true resolves the problem, but there is still a problem somewhere.

**Comment by JimiC** [comment]
`F1 > Apply Icons Customization` should always fix any issues.

**Comment by JimiC** [comment]
The only case I can think of is when the extension fails to be loaded after the icon-manifest was rebuild. In that case, the icons are displayed as they were in the previous icon-manifest. A useful move would be to navigate to the editor's menu `Help > Toggle Developer Tools` and post any errors logged.
