### ISSUE TITLE
Calling to all our fellow translators

### ISSUE THREAD

**Issue by robertohuertasm** [vscode-icons/vscode-icons#1796]
Hi friends, 

we have two new keys to be translated and we need (again) your help in order to make the new `8.0.0` release a reality.

The keys are `ngDetectedPresetFalse` and `nonNgDetectedPresetTrue`.

We're calling for help to:

- [x] :fr: @MonsieurMan
- [ ] :de: @jens1o
- [x] :it: @mariotsi @sabinrimni
- [x] :jp: @kimushu
- [x] :brazil: @cgarbin
- [x] :ru: @ksvitkovsky
- [x] :cn: @iFun @g-plane
- [x] :es: @robertohuertasm
- [ ] :tr: @kendinikertenkelebek

Btw, if you happen to be `Korean` and want to support this project by providing proper translations for your language, get in touch with us by answering to this thread. We'll be very glad to talk to you! 😉

**Comment by jens1o** [comment]
You can update the phrases here: https://crowdin.com/project/vscode-icons-i18n

**Comment by MonsieurMan** [comment]
By the way, I noticed something while translating. We have a `Restart` and an `Auto-restart` keys and they happen to be used also in the two new strings, and three old news but not via the variable.  

IMO, we should use the variable in these strings to prevent fragmentation in the translations : 
```markdown
- %extensionName% has detected an Angular project, but the 'preset' setting is set to 'false'. It's highly recommended to remove the 'preset' from the settings entirely. Selecting **'Restart'** will disable the Angular icons.
- %extensionName% has detected a non Angular project, but the 'preset' setting is set to 'true'. It's highly recommended to remove the 'preset' from the settings entirely. Selecting **'Restart'** will enable the Angular icons.
- %extensionName% has detected a non Angular project. Select **'Restart'** to disable the Angular icons.
- %extensionName% has detected an Angular project. Select **'Restart'** to enable the Angular icons.
- Select **'Restart'** for changes to take effect.
```
As I see it, it always mirror the text of the button so it should always be the same right ?

*PS: Thanks @jens1o, for the link !*

**Comment by JimiC** [comment]
@MonsieurMan Not sure what you mean.

**Comment by JimiC** [comment]
I have left some comments about your translations. Please have a look.
/cc @jens1o @mariotsi

**Comment by ksvitkovsky** [comment]
Done 😉

**Comment by JimiC** [comment]
@mariotsi @ksvitkovsky Thank you.

**Comment by JimiC** [comment]
@jens1o I left another comment at `Crodwin`. Posting here because `Crodwin` doesn't seem to push notifications.

**Comment by robertohuertasm** [comment]
@JimiC, what @MonsieurMan suggest is to use the original translation of `Restart` and `Auto-restart` keys in the text of these news translations. The thing is that I don't know if this is feasible using Crowdin. My guess is that it isn't but we could investigate.

**Comment by JimiC** [comment]
It's too complicated and not worth the hassle.

**Comment by MonsieurMan** [comment]
@robertohuertasm, yup :+1: 

I was just notifying that, in my case and I think it's the same for all translations, if I didn't check the old translations again, the button wouldn't have the same label as the text in the notification. Which would be really misleading.  

Anyway, as you say, it doesn't seem possible with crowdin, I thought that was what variables were for.

**Comment by iFun** [comment]
chinese submitted

**Comment by jens1o** [comment]
@JimiC I fixed it.

**Comment by robertohuertasm** [comment]
@cgarbin and @kendinikertenkelebek still missing. Let's hope they can find a moment to update the translations soon! 😜

**Comment by JimiC** [comment]
@cgarbin @kendinikertenkelebek Any follow up?
