### ISSUE TITLE
Getting a warning "The integrity of the extension is compromised"

### ISSUE THREAD

**Issue by gwynjudd** [vscode-icons/vscode-icons#2165]
- [x] I'm sure this issue is not a _duplicate_.

I've just started to get this warning in VSCode, associated with the extension:

![image](https://user-images.githubusercontent.com/314188/62015878-06c91c00-b203-11e9-81a5-ef5cb8530547.png)

Not really sure what it means, or the implications. Any guidance?

**Comment by MarkSky** [comment]
Today, I updated this extension to the version 9.0.0, and I alse got this warning!
My VSCode version is 1.36.1

**Comment by zxysilent** [comment]
me too

**Comment by autoferrit** [comment]
I got it as well when updating to the latest vscode insiders.

![image](https://user-images.githubusercontent.com/89895/62021239-1d2b9500-b17b-11e9-85fa-a50583837ed8.png)

**Comment by Corsario-Mexico** [comment]
Same here
![image](https://user-images.githubusercontent.com/33080295/62022008-cc726700-b18f-11e9-9cf5-1a74b407b214.png)

**Comment by pizzacrystal** [comment]
vs code 1.36.1, icons 9.0.0, same

**Comment by jasonsbarr** [comment]
VS Code 1.36.1, icons 9.0.0, me too.

**Comment by zhouzhili** [comment]
me too

**Comment by heunghingwan** [comment]
same

**Comment by dlordi** [comment]
same issue, both on VSCode 1.36.1 and VSCode Insiders 1.37.0

**Comment by JimiC** [comment]
In `v9` we introduced a new feature that does an integrity check of the extension core files installation. The message you are seeing is an indication that the integrity of those files is compromised in some way. 

This message does not prevent you from using the extension but is just a warning to make you aware that something is wrong.

The integrity checker checks the integrity of the following files:
- The entire `icons` directory
- The bundled extension's code: `dist/src/vscode-icons.bundle.js`
- The bundled language file: `lang.nls.bundle.json`
- The `nls` translation files: `package.nls.*.json`

If you tamper with any of those files the warning message gets shown.

I'm sure that some of you will claim that you haven't changed any of those files. In that case, it would be nice if you could post what `os` you are using in case this is an `os` specific issue.

Note: the feature has been tested on `linux` and didn't found any issues (this doesn't mean that there aren't any).

**Comment by a1p4ca** [comment]
I have same issue on windows 10

**Comment by DanJBower** [comment]
Hi @JimiC 

I too started getting this pop up after updating. I also freshly installed the extension which made no effect and I do not believe I have changed any of the files you mentioned.

I am running on Windows 10 Version 1903 (OS Build 18362.239) and version 1.36.1 of VSCode

**Comment by Harag9** [comment]
> In `v9` we introduced a new feature that does an integrity check of the extension core files installation. The message you are seeing is an indication that the integrity of those files is compromised in some way.
> 
> This message does not prevent you from using the extension but is just a warning to make you aware that something is wrong.
> 
> The integrity checker checks the integrity of the following files:
> 
> * The entire `icons` directory
> * The bundled extension's code: `dist/src/vscode-icons.bundle.js`
> * The bundled language file: `lang.nls.bundle.json`
> * The `nls` translation files: `package.nls.*.json`
> 
> If you tamper with any of those files the warning message gets shown.
> 
> I'm sure that some of you will claim that you haven't changed any of those files. In that case, it would be nice if you could post what `os` you are using in case this is an `os` specific issue.
> 
> Note: the feature has been tested on `linux` and didn't found any issues (this doesn't mean that there aren't any).

Hi JimiC.

I'm on v1.36.1 of VS Code and it just updated the extension to v9 and I'm also now getting this warning message - I'm one of those that claim I haven't changed any of those files you mentioned so not sure why I'm getting the message.

I'm currently on Windows 10 Enterprise x64 - Version 1803 - OS Build 17134.885

Hope this helps.

**Comment by escamoteur** [comment]
Same issue on Windows 10. Tried to reinstall it no change

**Comment by dlordi** [comment]
> 
> 
> In `v9` we introduced a new feature that does an integrity check of the extension core files installation. The message you are seeing is an indication that the integrity of those files is compromised in some way.
> 
> This message does not prevent you from using the extension but is just a warning to make you aware that something is wrong.
> 
> The integrity checker checks the integrity of the following files:
> 
>     * The entire `icons` directory
> 
>     * The bundled extension's code: `dist/src/vscode-icons.bundle.js`
> 
>     * The bundled language file: `lang.nls.bundle.json`
> 
>     * The `nls` translation files: `package.nls.*.json`
> 
> 
> If you tamper with any of those files the warning message gets shown.
> 
> I'm sure that some of you will claim that you haven't changed any of those files. In that case, it would be nice if you could post what `os` you are using in case this is an `os` specific issue.
> 
> Note: the feature has been tested on `linux` and didn't found any issues (this doesn't mean that there aren't any).

I'm on Windows 10 Pro x64 ver 1903 (build SO 18362.239)

**Comment by Omniusz** [comment]
Same issue. I have not messed with any files or folders.

![image](https://user-images.githubusercontent.com/16664707/62037698-3882b880-b1ec-11e9-977e-1bab5f57bf48.png)

**Comment by JimiC** [comment]
So it looks like it's a `Windows` related issue. I'll investigate this further. I suspect that it has something to do with the path separator but it's just my speculation.

I would like to ask you to not post any new comments until we have something new to report. Otherwise I will be forced to lock the issue. Thank you in advance.

**Comment by biltongza** [comment]
I am getting it on an Arch Linux VM via SSH to a Windows host:
`Linux arch 5.2.0-arch2-1-ARCH #1 SMP PREEMPT Mon Jul 8 18:18:54 UTC 2019 x86_64 GNU/Linux`
```
Version: 1.36.1 (system setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362```

**Comment by Myugen** [comment]
Same issue on Windows 10, VSCode 1.36.1.

**Comment by JimiC** [comment]
**Update:** Issue cause has been identified. Working on a fix.

**Comment by dregimbal** [comment]
> 
> 
> **Update:** Issue cause has been identified. Working on a fix.

What was the issue/cause?

**Comment by JimiC** [comment]
The difference of files listing order between `*nix` and `Windows`. :man_facepalming:

**Comment by JimiC** [comment]
Fix submitted. Hopefully, @robertohuertasm will do a patch release in a few hours.

**Comment by JimiC** [comment]
Thank you, everybody, for your patience.

**Comment by jslomkowski** [comment]
Hi,
The issue is back in version 11.1.0 on Windows.
If I roll back to 11.0.0 it's ok

**Comment by MatievisTheKat** [comment]
Getting this issue on Ubuntu 20.04 with v11.1.0 (VSCode v1.53.2.)
Reinstalling doesn't change anything.
Rolling back to v11.0.0 seems to fix it

**Comment by winstonhenke** [comment]
Have had this issue for a few weeks now on macOS
macOS Big Sur: 11.2.2 (20D80)
VS Code: Version: 1.54.1 Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8

**Comment by jamierajewski** [comment]
I can confirm it is happening on Pop OS 20.10
VSCode 1.54.2
Extension version 11.2.0

**Comment by winstonhenke** [comment]
They released v11.2.0 a couple days ago and I have not seen this issue since then

**Comment by jamierajewski** [comment]
I just tried uninstalling and reinstalling it (even though I already had the latest) and it still shows up, as you can see in the bottom right corner of the attached screenshot:
![Screenshot from 2021-03-17 11-13-57](https://user-images.githubusercontent.com/25068017/111509092-fc2e0400-8711-11eb-8c7a-11b270873b2b.png)

**Comment by MatievisTheKat** [comment]
I have not seen this issue since v11.2.0

**Comment by bimp** [comment]
Just got this message with latest update. Would this message appear if I run VS Code Portable from a OneDrive directory that I use across my desktop and laptop?

**Comment by bimp** [comment]
I rolled back from 11.2.0 back to 11.1.0 and message went away. Disabling auto updates for now

**Comment by mpatkinson7** [comment]
I've been having this issue for months. Was completely sick of it. I finally took the time to dig around (Google), landed here, and discovered when I rolled the vscode-icons back to 11.1.0 it fixed the problem. Woohoo!!! I also turned off the 'Auto Check Updates' and 'Auto Update' so I don't get the problem back or the annoying prompt to update.

**Comment by robertohuertasm** [comment]
We'll investigate if this is related to the `nsri` version as the last time. Maybe it would make sense to disable this check while it's unreliable.

**Comment by mpatkinson7** [comment]
Thanks very much for looking into this. Appreciated.

**Comment by bimp** [comment]
> 
> 
> We'll investigate if this is related to the `nsri` version as the last time. Maybe it would make sense to disable this check while it's unreliable.

thanks for investigating... love this extension!

**Comment by mpatkinson7** [comment]
> Well, it seems that @JimiC hasn't updated the `nsri` package in months, so that makes it unlikely that it's something related to that dependency. Most probably, there is something tampering some of the [no nsri ignored files](https://github.com/vscode-icons/vscode-icons/blob/master/.nsriignore). Are you using custom icons? Have you changed somehow some of those files? Do you have any kind of extension that changes vscode files?

Thanks for your efforts. I’m definitely not using custom icons, nor changed any of the files. The only extensions I run are the Python extension, Python-autopep8 & the vscode-icons extension. That’s it. I was having the same issue on my work PC too. Unlike home, where VS Code is installed, work is a portable version - if that helps?

**Comment by robertohuertasm** [comment]
@mpatkinson7 thanks for the feedback. Do you mean that you're only getting this on portable version? I mean, your home vscode works as expected?

**Comment by mpatkinson7** [comment]
@robertohuertasm Welcome. No, unfortunately I mean the problem is occurring on both the home & work machines.

**Comment by bimp** [comment]
@robertohuertasm I only have experience(< 1 month) using VSCode in only the portable mode. I have dumped my entire portable installation into a OneDrive folder that I use across 2 laptops and a desktop. This works great BTW.

I do have the Terraform extension (installed BEFORE vscode icons extension) from https://github.com/4ops/vscode-language-terraform that added its own icons. But then i installed vscode icons extension and noticed those terraform icons for my terraform/terragrunt files went away. I then modified vscode icons settings.json file to get them back via:

```
"vsicons.associations.files": [
        {
            "icon": "terraform",
            "extensions": ["tf","tfvars"],
            "format": "FileFormat.svg",
        }
    ],
```

**Comment by bimp** [comment]
Well now I'm getting that warning message again with version v11.1.0 :-(

**Comment by robertohuertasm** [comment]
Hi, a new version has been release that hopefully will avoid the issues with integrity warnings in portable mode. @bimp, @mpatkinson7 let us know if everything is ok with this new version.

**Comment by mpatkinson7** [comment]
Thanks very much for that @robertohuertasm. FYI: I think I discovered what the problem was "for me". I had no issues on the older version (11.1.0) UNTIL I ran a program called BleachBit (https://www.bleachbit.org/). I basically run the program from time to time - just to clear guff from PC. After running it last night and starting VS Code, I noticed the 'integrity of the extension' issue appeared again. I didn't repeat the process or investigate further (busy life & limited time), but I'm pretty sure BleachBit was the root cause. I've since uninstalled BleachBit (went back to CCleaner & running this didn't cause any issues). I'm now running vscode-icons 11.4.0 and having no problems. If this changes, I will repost.
Thanks again.

**Comment by robertohuertasm** [comment]
@mpatkinson7 glad to hear you fixed the issue on your side. Hopefully, this new release will fix the issue for good for everyone else. I'm closing this issue for now. Feel free to ping us in case this happens again.

**Comment by mpatkinson7** [comment]
No worries. Thanks very much @robertohuertasm

**Comment by robertohuertasm** [comment]
Thanks also to @JimiC who was investigating the issue and provided a solution in his spare free time!

**Comment by bimp** [comment]
@robertohuertasm @JimiC thanks... looks to have been fixed with my portable OneDrive installation setup. Thanks!

**Comment by GavHern** [comment]
![image](https://user-images.githubusercontent.com/47736824/115125018-61c41900-9f7a-11eb-9b1c-42656af6131d.png)

Still getting this issue. Started happening after I reinstalled windows and visual studio code. reinstalling the extension or the editor does nothing...

**Comment by ujwal-setlur** [comment]
I am getting this issue on the latest version of VS Code.

**Comment by creage** [comment]
12.7.0 - same issue. Most of icons are missing.

**Comment by Ellivers** [comment]
Getting the same issue. Icons seem to work fine.
Extension version 12.9.0 VSCode version 1.94.2 Windows 10
